name: Check Script and Playbook Updates

on:
  pull_request:
    paths:
      - 'scripts/**'

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Check if scripts/ were updated without corresponding updates in playbooks/
      run: |
        BASE_COMMIT=${{ github.event.pull_request.base.sha }}
        HEAD_COMMIT=${{ github.event.pull_request.head.sha }}

        changed_files=$(git diff --name-only "$BASE_COMMIT" "$HEAD_COMMIT")

        # Check if any files in scripts/ were updated
        scripts_updated=$(echo "$changed_files" | grep 'scripts/' || true)
        echo "Scripts updated: $scripts_updated"

        # Check if any files in playbooks/ were updated
        playbooks_updated=$(echo "$changed_files" | grep 'playbooks/' || true)
        echo "Playbooks updated: $playbooks_updated"

        if [[ -n "$scripts_updated" && -z "$playbooks_updated" ]]; then
          echo "Files in scripts/ were updated without corresponding updates in playbooks/"
          exit 1
        fi

        echo "Check passed"
